name: food_x
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cached_network_image: ^3.3.0
  cupertino_icons: ^1.0.2
  dio: ^5.3.3
  firebase_auth: ^4.6.3
  firebase_core: ^2.14.0
  firebase_dynamic_links: ^5.3.6
  flutter_barcode_scanner: ^2.0.0
  flutter_bloc: ^8.1.3
  flutter_local_notifications: ^15.1.1
  flutter_native_splash: ^2.3.2
  flutter_secure_storage: ^9.0.0
  flutter_svg: ^2.0.7
  google_sign_in: ^6.1.4
  go_router: ^10.1.2
  image_picker: ^1.0.4
  intl: ^0.18.1
  json_annotation: ^4.8.1
  rxdart: ^0.27.7
  timezone: ^0.9.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  json_serializable: ^6.7.1

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/splash.png

flutter:
  uses-material-design: true

  assets:
    - assets/splash.png
    - assets/icons/
    - assets/images/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
    - family: Poppins-Light
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
    - family: Poppins-Bold
      fonts:
        - asset: assets/fonts/Poppins-Bold.ttf